Repository swcarpentry/python-novice-inflammation, pull requests merged in 2018-10, with the labels that each got.

#556 README.md: add 'About the Lesson' section
  README.md
Labels: high priority, type:enhancement

#587 fix long lines _episodes/03-lists.md #498
  _episodes/03-lists.md
Labels: status:changes requested

#591 refactor python-overlapping-ranges.svg source, remove odg file (towards #494)
  fig/python-overlapping-ranges.odg
  fig/python-overlapping-ranges.svg
Labels: status:in progress

#590 06-func.md: fix long lines and other fixes
  _episodes/06-func.md
Labels: type:formatting

#592 01-numpy.md: simplify wording
  _episodes/01-numpy.md
Labels: type:clarification
