Repository swcarpentry/python-novice-inflammation, pull requests merged in 2019-07, with the labels that each got.

#686 03-lists.md: Use `pop()` for consistency of method over statement
  _episodes/03-lists.md
Labels: type:enhancement

#660 Stressed that functions do not need to return a value. Issue #489.
  _episodes/06-func.md
  reference.md
Labels: status:in progress

#688 Moved note on importing numpy as np
  _episodes/01-numpy.md
Labels: status:changes requested, type:enhancement
