Repository swcarpentry/python-novice-inflammation, pull requests merged in 2019-09, with the labels that each got.

#705 Update 08-defensive.md: exercise time
  _episodes/08-defensive.md
Labels: type:enhancement

#708 Update 09-debugging.md: exercise time
  _episodes/09-debugging.md
Labels: type:enhancement

#712 Update 06-func.md: visualize() vs analyze()
  _episodes/06-func.md
Labels: status:changes requested, type:enhancement

#719 Update MatPlotlib-generated figures in NumPy episode
  _episodes/01-numpy.md
  fig/01-numpy_71_0.png
  fig/01-numpy_73_0.png
  fig/01-numpy_75_1.png
  fig/01-numpy_75_3.png
  fig/01-numpy_80_0.png
  fig/01-numpy_exercise_0.png
  fig/generate_figures.py
  fig/inflammation-01-average.svg
  fig/inflammation-01-group-plot.svg
  fig/inflammation-01-imshow.svg
  fig/inflammation-01-line-styles.svg
  fig/inflammation-01-maximum.svg
  fig/inflammation-01-minimum.svg
  fig/optimize_svg.py
Labels: high priority

#720 Missing glob import in example
  _episodes/04-files.md
Labels: type:bug
