Repository swcarpentry/python-novice-inflammation, pull requests merged in 2019-02, with the labels that each got.

#614 Resolve iPython vs. Jupyter Notebook ambiguity
  _episodes/01-numpy.md
Labels: type:enhancement

#617 Fix Python capitalization
  _episodes/07-errors.md
Labels: type:typo text

#615 Rename variables in `range_overlap` function
  _episodes/08-defensive.md
Labels: status:changes requested, type:enhancement

#594 02-loop.md: Another reason why for loops are useful
  _episodes/02-loop.md
Labels: status:changes requested, type:enhancement

#612 Adds a table of episodes to README
  README.md
Labels: type:enhancement

#613 Adds LICENSE section and links to Instructor Notes to README
  README.md
Labels: type:enhancement

#620 README.md: Episode table: add 'Time' column
  README.md
Labels: status:in progress

#626 Update Loops Episode in conjunction with loops/lists switch
  _episodes/03-loop.md
  fig/03-loops_image_num.png
Labels: Lists - Loops
